server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_management_spring_graphql?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  output:
    ansi:
      enabled: always